
features_details:
  age: "The age of the person in years. It is represented as a numerical value. (Numerical - Integer)"
  workclass: "The type of workclass the person belongs to, such as Private, Self-emp-not-inc, Self-emp-inc, etc. It is represented as a categorical variable. (Categorical - String)"
  fnlgt: "The final weight assigned to each observation after data sampling. It is used to correct for the unequal representation of classes. It is represented as a numerical value. (Numerical - Integer)"
  education: "The highest level of education completed by the person, such as Bachelors, Masters, Doctorate, etc. It is represented as a categorical variable. (Ordinal Categorical - String)"
  education_num: "The highest level of education completed by the person, represented as a numerical value. It provides a mapped numerical representation of the education levels. (Ordinal Categorical - Integer)"
  marital_status: "The marital status of the person, such as Married-civ-spouse, Divorced, Never-married, etc. It is represented as a categorical variable. (Nominal Categorical - String)"
  occupation: "The occupation of the person, such as Tech-support, Craft-repair, Sales, etc. It is represented as a categorical variable. (Nominal Categorical - String)"
  relationship: "The relationship of the person in the household, such as Husband, Wife, Own-child, etc. It is represented as a categorical variable. (Nominal Categorical - String)"
  race: "The race of the person, such as White, Black, Asian-Pac-Islander, etc. It is represented as a categorical variable. (Nominal Categorical - String)"
  sex: "The gender of the person, either Male or Female. It is represented as a categorical variable. (Nominal Categorical - String)"
  capital_gain: "The capital gain of the person from investments or property sales. It is represented as a numerical value. (Numerical - Integer)"
  capital_loss: "The capital loss of the person from investments or property sales. It is represented as a numerical value. (Numerical - Integer)"
  hours_per_week: "The number of hours worked per week by the person. It is represented as a numerical value. (Numerical - Integer)"
  native_country: "The native country of the person, such as United-States, Mexico, Philippines, etc. It is represented as a categorical variable. (Nominal Categorical - String)"


post_examples:
  Class >50k (indicated with Label [1]):
    summary: "An example of class >50k"
    description: "A example that should predict a class of >50k"
    value: 
      age: 45
      workclass: "State-gov"
      fnlgt: 448512
      education: "bachelors"
      education_num: 14
      marital_status: "Divorced"
      occupation: "prof-specialty"
      relationship: "wife"
      race: "Black"
      sex: "female"
      capital_gain: 0
      capital_loss: 0
      hours_per_week: 60
      native_country: "taiwan"

  Class <=50k (indicated with Label [0]:
    summary: "An example of an individual with an income of <=50k."
    description: "This example represents an individual with various characteristics that are used to predict their income level."
    value: 
      age: 37
      workclass: "Self-emp-inc"
      fnlgt: 32165
      education: "masters"
      education_num: 13
      marital_status: "Married"
      occupation: "adm-clerical"
      relationship: "Husband"
      race: "Asian-Pac-Islander"
      sex: "male"
      capital_gain: 2174
      capital_loss: 0
      hours_per_week: 40
      native_country: "united-states"

  Missing sample: 
    summary: "An example of a sample with missing values"
    description: "This example showcases the model's ability to handle missing values for certain features"
    value: 
      age: 81
      fnlgt: 120478
      education_num: 11
      capital_gain: 0
      capital_loss: 0
      hours_per_week: 1

  Error sample:
    summary: "An example of a sample that will cause an error"
    description: "This example represents a sample that will cause an error with the model due to missing age and fnlgt variables."
    value:
      workclass: "local-gov"
      education: "assoc-voc"
      education_num: 11
      marital_status: "divorced"
      occupation: "prof-specialty"
      relationship: "unmarried"
      race: "white"
      sex: "female"
      capital_gain: 0
      capital_loss: 0
      hours_per_week: 1
      native_country: "taiwan"