name: CI # Name of the Action

on: [push] 

jobs:
  build:

    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.8] 

    steps:
    - uses: actions/checkout@v2 
    - name: Set up Python ${{ matrix.python-version }} # Name of an action that sets up Python
      uses: actions/setup-python@v2 # A pre-built GitHub Action that sets up a Python environment
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # If we have a requirements.txt, then install it
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: AKIAQZLQB33GPPBDRVES
    #     aws-secret-access-key: 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
    #     aws-region: eu-north-1
    #     role-duration-seconds: 500
    #     role-session-name: Github_Action
    # - name: DVC install
    #   uses: iterative/setup-dvc@v1
    # - name: DVC pull
    #   run: |
    #     dvc pull 
    # - name: Test with pytest # Final action which runs pytest. If any test fails, then this Action fails
    #   run: |
    #     pytest starter/src/pipeline -vv

    - name: Test with pytest # Final action which runs pytest. If any test fails, then this Action fails
      run: |
        pytest starter/src/app -vv
