name: CI # Name of the Action
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: [3.9.13] 

    steps:
    - uses: actions/checkout@v2 
    
    # Setting up the environment 
    - name: Set up Python ${{ matrix.python-version }} environment
      uses: actions/setup-python@v2                       
      with:
        python-version: ${{ matrix.python-version }}

    # Install required packages 
    - name: Install required dependencies with [pip]
      run: |
        python -m pip install --upgrade pip                                     # Upgrade pip to the latest version
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    # Install requirements.txt if existed 

    # Linting submitted code with flake8
    - name: Lint code with [flake8]
      run: |
        flake8 . --count --show-source --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # Configuring AWS client for DVC    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQZLQB33GPPBDRVES
        aws-secret-access-key: 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
        aws-region: eu-north-1
        role-duration-seconds: 500
        role-session-name: Github_Action
    
    # Instaling DVC Packages and pull latest bucket content 
    - name: DVC install packages
      uses: iterative/setup-dvc@v1
    
    # Pulling latest bucket content 
    - name: DVC pull
      run: |
        dvc pull 
    
    # Validating submitted pipeline and APIs
    - name: Test Pipeline & APIs with pytest    
      run: |
        python -m pytest starter/src/testing/test_model.py -vv --disable-warnings --import-mode=append

    # Validating submitted pipeline and APIs
    - name: Test Pipeline & APIs with pytest    
      run: |
        python -m pytest starter/src/testing/test_api.py -vv --disable-warnings --import-mode=append
